pip install wolframalpha
pip install wikipedia
pip install SpeechRecognition
pip install ecapture
pip install twilio
pip install beautifulsoup4
pip install pyttsx3
pip install requests
pip install pyjokes
pip install winshell
pip install feedparser
pip install clint
pip install pyaudio